### PR TITLE
Migrate to go modules

### PR DESCRIPTION
**Pull request by richardwxn**
For issue: istio/istio#15240. Create from @kramerul commit

### CODE REVIEW

**Comment by geeknoid** [comment]
Could  you  rebase this PR please?

Thanks.

**Comment by geeknoid** [comment]
Oh, I thought this was deleting the vendor dir, but it's still there. Can we nuke it? When I do so locally, everything builds happily.

**Comment by richardwxn** [comment]
@geeknoid yep I am creating another PR to clean that up entirely

**Pull request merged**
