### PR TITLE
add serviceAnnotation to KubernetesResourcesSpec.

### PR DESCRIPTION
**Pull request by morvencao**
resubmit: https://github.com/istio/operator/pull/736 due to https://github.com/istio/operator/pull/713 
depends on: https://github.com/istio/api/pull/1230

### CODE REVIEW

**Comment by elfinhe** [comment]
lgtm

**Review by elfinhe — COMMENTED** [review]
maybe we need to wait until the tests on master gets fixed?

**Comment by morvencao** [comment]
These failed tests depend on https://github.com/istio/api/pull/1230

**Review by elfinhe — APPROVED** [review]

**Pull request merged**
