### PR TITLE
Update common files.

### PR DESCRIPTION
**Pull request by geeknoid**

### CODE REVIEW

**Comment by ericvn** [comment]
Argh @geeknoid. Looking at my common-files PR that included the changes wasn't targeted for master but the forOperator branch. My bad I guess. I'll need to recreate the PR I think.

**Comment by morvencao** [comment]
@sdake Sure.

**Comment by sdake** [comment]
> Argh @geeknoid. Looking at my common-files PR that included the changes wasn't targeted for master but the forOperator branch. My bad I guess. I'll need to recreate the PR I think.

thanks for taking on the convergence of my work with @geeknoid 's work in https://github.com/istio/common-files/pull/21.

I expect we will roll out new updates of common-files as time passes.  The immediate goal is to get this structure rolled out across the various repositories in a way that doesn't break the existing repos.  This PR should do that - as it disables the docker build trial by default and makes opt-in a feature.

Cheers
-steve

**Comment by sdake** [comment]
> #167 has been merged, please rebase to resolve the linter issue.

rebases are not required with repos on the tide plan.

**Pull request merged**
