### PR TITLE
[release 1.4] Update installer

### PR DESCRIPTION
**Pull request by sdake**
Use 1.4 hash:
a6e4a4b3087ffd1bce5b186c0e3bd49cf2ee40a0

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by sdake** [comment]
@ostromart how do I get the mandiff check passing? Seems like `make gen` should be sufficient?

Cheers
-steve

**Review by ericvn — APPROVED** [review]

**Comment by ericvn** [comment]
Looks like I duplicated your PR with my #501 which I can close. Hitting the same handoff check.

**Comment by linsun** [comment]
@sdake looking at the test failure, i think it complained the helm generated yaml for default profile (https://github.com/istio/operator/blob/release-1.4/tests/profiles/helm/values-istio-default.yaml) with the yaml generated from the icp default profile (https://github.com/istio/operator/blob/release-1.4/data/profiles/default.yaml).

Should we update the icp default profile (https://github.com/istio/operator/blob/release-1.4/data/profiles/default.yaml) with dns cert provisioning disabled to match what is changed in installer by @lei-tang?

**Comment by linsun** [comment]
@sdake I think we need to make these empty array:

https://github.com/istio/operator/blob/release-1.4/data/profiles/default.yaml#L312

**Comment by lei-tang** [comment]
@linsun https://github.com/istio/operator/pull/500

**Comment by linsun** [comment]
Thanks @lei-tang - we need to wait that is merged then cherry pick PR is merged before this one can pass the test.

**Comment by ericvn** [comment]
Looks like that PR is also failing the mandiff test.

**Comment by ostromart** [comment]
For mandiff to pass, two things are needed:
1. run make update-goldens locally to refresh the test outputs (if there were any chart changes)
2. make any required changes in the data/profiles/default.yaml profile to reflect the same changes in installer (if appropriate).
e.g. have a look at this pr: https://github.com/istio/operator/pull/482
That latter requirement is quite painful and for this and other reasons we should consider merging the charts with operator.

**Comment by sdake** [comment]
addressed in https://github.com/istio/operator/pull/500 - so closing this PR.  Thanks @lei-tang for sorting out master and the backport of this issue.

Cheers
-steve

**Pull request closed without merging**
