### PR TITLE
update minimal profile

### LINKED ISSUE #19039: Pilot errors on minimum install
**Bug description**

Cannot install "minimum" profile on GKE. Installation "succeeds", but pilot stays at 1/2 containers ready, and eventually starts restarting...

I just came across this using istioctl 1.4.0 and the --profile minimum, and pilot doesn't want to come up.

from discovery container

```
...
2019-11-17T21:33:37.222333Z     info    mcp     (re)trying to establish new MCP sink stream
2019-11-17T21:33:37.222487Z     error   mcp     Failed to create a new MCP sink stream: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:15019: connect: connection refused"
```

from istio-proxy container

```
...
2019-11-17T21:34:09.063949Z     info    waiting for file
```

**Expected behavior**

Pilot comes up, is ready, and no errors are logged.

**Steps to reproduce the bug**

```bash
MY_HOME_IP="$(curl https://ifconfig.co/ip)"
PROJECT_NAME="kubernetes-on-the-cheap"
REGION="us-west1"
ZONE_ID="a"
ZONE="${REGION}-${ZONE_ID}"

gcloud beta container \
  --project "${PROJECT_NAME}" \
  clusters create "hobby-1" \
  --zone "${ZONE}" \
  --no-enable-basic-auth \
  --release-channel "regular" \
  --machine-type "g1-small" \
  --image-type "COS" \
  --disk-type "pd-standard" \
  --disk-size "30" \
  --metadata disable-legacy-endpoints=true \
  --scopes "https://www.googleapis.com/auth/devstorage.read_only","https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring","https://www.googleapis.com/auth/servicecontrol","https://www.googleapis.com/auth/service.management.readonly","https://www.googleapis.com/auth/trace.append" \
  --preemptible \
  --num-nodes "1" \
  --enable-stackdriver-kubernetes \
  --enable-ip-alias \
  --network "projects/${PROJECT_NAME}/global/networks/default" \
  --subnetwork "projects/${PROJECT_NAME}/regions/${REGION}/subnetworks/default" \
  --default-max-pods-per-node "110" \
  --enable-master-authorized-networks \
  --master-authorized-networks "${MY_HOME_IP}/32" \
  --addons HorizontalPodAutoscaling \
  --enable-autoupgrade \
  --enable-autorepair \
  --maintenance-window-start "2019-11-15T10:00:00Z" \
  --maintenance-window-end "2019-11-15T14:00:00Z" \
  --maintenance-window-recurrence "FREQ=WEEKLY;BYDAY=MO,TU,WE,TH"

curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.4.0 sh -
echo 'export PATH="$PATH:$HOME/istio-1.4.0/bin"' >> ~/.bashrc

kubectl create clusterrolebinding cluster-admin-binding \
    --clusterrole=cluster-admin \
    --user=$(gcloud config get-value core/account)

istioctl manifest apply --set profile=minimal

k -n istio-system patch deployment istio-pilot --patch '{"spec":{"template":{"spec":{"$setElementOrder/containers":[{"name":"discovery"},{"name":"istio-proxy"}],"containers":[{"name":"discovery","resources":{"requests":{"cpu":"10m","memory":"100Mi"}}},{"name":"istio-proxy","resources":{"limits":null,"requests":null}}]}}}}'
```

optional next steps is to delete the original replica set so you don't see a pending pod (that is requesting more resources than what's available)

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
istioctl version --remote
client version: 1.4.0
control plane version: 1.4.0
data plane version: none
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.12", GitCommit:"188432a69210ca32cafded81b4dd1c063720cac0", GitTreeState:"clean", BuildDate:"2019-11-07T19:27:01Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

see repro steps above.

**Environment where bug was observed (cloud vendor, OS, etc)**

GCP GKE

### PR DESCRIPTION
**Pull request by richardwxn**
Should be able to resolve: https://github.com/istio/istio/issues/19039

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
did you verify this works?

**Comment by richardwxn** [comment]
@howardjohn yep it works

**Pull request merged**
