### PR TITLE
Turn off DNS certificate provisioning

### PR DESCRIPTION
**Pull request by lei-tang**
This PR is for the issue: https://github.com/istio/istio/issues/18456

### CODE REVIEW

**Review by morvencao — COMMENTED** [review]
You need to refresh golden files to make the test pass by adding `REFRESH_GOLDEN=true` env before running the `make test`.

**Review by linsun — APPROVED** [review]

**Comment by linsun** [comment]
Good catch thank you @morvencao

**Comment by lei-tang** [comment]
@morvencao Thank you! I have revised the PR accordingly.

**Comment by lei-tang** [comment]
@ostromart, @richardwxn, @morvencao after running the following commands and including the diffs, there are still test failures (gencheck_operator, mandiff_operator). Are there instructions on what commands need to be ran after making a change to the default profile? Thanks!

export REFRESH_GOLDEN=true
make gen
make update-goldens
make test
make gen-check

**Comment by morvencao** [comment]
@lei-tang Try to update the [installer.sha](https://github.com/istio/operator/blob/master/installer.sha) to `a4241599ca243b2cc6bdfd28fb45c26709143438` to include [your changes](https://github.com/istio/installer/pull/471) in installer repo.

**Comment by ericvn** [comment]
Verified locally, that just the change @morvencao mentioned fixes the failing test case.

**Comment by lei-tang** [comment]
@morvencao @ericvn Thank you! I pushed a commit after updating the installer.sha.

**Pull request merged**
