### PR TITLE
Move translations info table into translateConfig-1.3.yaml

### PR DESCRIPTION
**Pull request by irisdingbj**
https://github.com/istio/istio/issues/17238

### CODE REVIEW

**Review by ostromart — APPROVED** [review]
Great work Iris, thank you!

**Comment by ostromart** [comment]
test_operator is failing because prometheus: enabled is flipping between true and false for some reason - I haven't yet investigated further.

**Comment by irisdingbj** [comment]
> test_operator is failing because prometheus: enabled is flipping between true and false for some reason - I haven't yet investigated further.

@ostromart  PrometheusOperator and Prometheus have the same path `prometheus.enabled` defined in their Values.yaml: https://github.com/istio/installer/blob/master/istio-telemetry/prometheus-operator/values.yaml  this is reason why it is flipping.  Sorting the components for now to bypass the issue. Wondering do we need to fix this in installer's repo to make the path in `Values.yaml` for them are different?

**Comment by ostromart** [comment]
The problem is more with how we are using the charts - installer does not define prometheus.enabled in global values. I think we should probably remove the per-chart values.yamls for the compiled-in charts to prevent this sort of hidden value problem in the future.

**Pull request merged**
