### PR TITLE
Simplify outputs, hide component details if no errors.

### PR DESCRIPTION
**Pull request by elfinhe**
Simplify outputs, hide component details if no errors.

Related: https://github.com/istio/istio/issues/19451

### CODE REVIEW

**Comment by howardjohn** [comment]
I am not sure why, but this doesn't work on my cluster.. maybe an unrelated change?

<details>

```
This will install the default Istio profile into the cluster. Proceed? (y/N) y
- Applying manifest for component Base...
✔ Finished applying manifest for component Base.
- Applying manifest for component Citadel...
- Applying manifest for component Prometheus...
- Applying manifest for component IngressGateway...
- Applying manifest for component Policy...
- Applying manifest for component Galley...
- Applying manifest for component Pilot...
- Applying manifest for component Injector...
- Applying manifest for component Telemetry...
✘ Finished applying manifest for component Prometheus.
✘ Finished applying manifest for component Pilot.
✘ Finished applying manifest for component Policy.
✘ Finished applying manifest for component Injector.
✘ Finished applying manifest for component Galley.
✘ Finished applying manifest for component Citadel.
✘ Finished applying manifest for component IngressGateway.
✔ Finished applying manifest for component Telemetry.

Component Citadel - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

error: no objects passed to apply (repeated 1 times)





Component Grafana - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

error: when paths, URLs, or stdin is provided as input, you may not specify resource arguments as well (repeated 1 times)





Component Galley - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

error: no objects passed to apply (repeated 1 times)





Component PrometheusOperator - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

error: when paths, URLs, or stdin is provided as input, you may not specify resource arguments as well (repeated 1 times)





Component NodeAgent - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

error: when paths, URLs, or stdin is provided as input, you may not specify resource arguments as well (repeated 1 times)





Component Pilot - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

error: no objects passed to apply (repeated 1 times)





Component EgressGateway - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

error: when paths, URLs, or stdin is provided as input, you may not specify resource arguments as well (repeated 1 times)





Component CertManager - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

error: when paths, URLs, or stdin is provided as input, you may not specify resource arguments as well (repeated 1 times)





Component Prometheus - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

error: no objects passed to apply (repeated 1 times)





Component Injector - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

error: no objects passed to apply (repeated 1 times)





Component Policy - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

error: no objects passed to apply (repeated 1 times)





Component IngressGateway - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

error: no objects passed to apply (repeated 1 times)





Component Kiali - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

error: when paths, URLs, or stdin is provided as input, you may not specify resource arguments as well (repeated 1 times)





Component Cni - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

error: when paths, URLs, or stdin is provided as input, you may not specify resource arguments as well (repeated 1 times)





Component CoreDNS - manifest apply returned the following errors:
Error: `kubectl get` returned a yaml whose kind is not List


Component Tracing - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

error: when paths, URLs, or stdin is provided as input, you may not specify resource arguments as well (repeated 1 times)





```

</details>

**Comment by howardjohn** [comment]
Looks like it happens at `master`. I think this looks  great, but haven't seen the output from success yet because of that issue

**Comment by elfinhe** [comment]
@howardjohn you are right, we need this fix pushed first: https://github.com/istio/operator/pull/679

**Comment by howardjohn** [comment]
Ah you are way ahead of me. Thanks!

**Review by ostromart — APPROVED** [review]

**Pull request merged**
