### PR TITLE
Update installer SHA and remove security.trustDomain

### PR DESCRIPTION
**Pull request by pitlv2109**
Related PR from installer https://github.com/istio/installer/pull/493

### CODE REVIEW

**Review by morvencao — COMMENTED** [review]
Run `make update-goldens` and `make gen` to make the tests pass.

**Comment by ostromart** [comment]
Actually you really need:
BUILD_WITH_CONTAINER=0 make update-goldens
make clean gen

**Review by ostromart — APPROVED** [review]

**Comment by ostromart** [comment]
@pitlv2109 don't forget to go through this for release-1.4 (use a sha from istio/installer:release-1.4)

**Comment by howardjohn** [comment]
I can sync up 1.4, need to land some other changes anyways

**Comment by pitlv2109** [comment]
@ostromart this change was merged in 1.4 some hours ago here https://github.com/istio/operator/pull/533, but it has some issue which I wrote a comment below.

**Pull request merged**
