### PR TITLE
Terminate yaml correctly

### PR DESCRIPTION
**Pull request by sdake**
Also address a few changes from PR: https://github.com/istio/istio.io/pull/5183

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by howardjohn** [comment]
this needs to be 1.4-dev for the backport though

**Comment by sdake** [comment]
> this needs to be 1.4-dev for the backport though

understood - see followup pr in a few minutes for test-infra.

**Comment by sdake** [comment]
https://github.com/istio/test-infra/pull/1972

**Comment by sdake** [comment]
manual backport as there were conflicts around 1.4-dev: https://github.com/istio/operator/pull/424

**Pull request merged**
