### PR TITLE
Update to common-files

### PR DESCRIPTION
**Pull request by sdake**

### CODE REVIEW

**Comment by sdake** [comment]
waiting to propogate local build container to test-infra.

**Review by ostromart — COMMENTED** [review]
Could you please check that make vfsgen works for linux after this change? I worry because we had problems with GOBIN before.

**Comment by sdake** [comment]
> Could you please check that make vfsgen works for linux after this change? I worry because we had problems with GOBIN before.

I tested all of the make targets (with BUILD_WITH_CONTAINER=1) prior to submission.  The gate checks BUILD_WITH_CONTAINER=0 for the most part.  I think this is GTG.  I am simply waiting on a build of the docker container that has a new prow entrypoint to push the operator container.  See PR: https://github.com/istio/tools/pull/428 https://github.com/istio/tools/pull/430.  Once these PRs regenerate a new image, I will install it in the checks.  Then this PR can merge (I will remove the hold I set) - and we should have published docker images on gcr.io (hopefully).

Cheers
-steve

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
