### PR TITLE
[release-1.4] Update installer SHA part #2. Missed make gen

### PR DESCRIPTION
**Pull request by ericvn**

### CODE REVIEW

**Review by jwendell — APPROVED** [review]

**Comment by howardjohn** [comment]
/hold

I think this needs `make clean` run

**Comment by howardjohn** [comment]
https://github.com/istio/operator/pull/774 might be what we want - the diff looks more correct at least

**Comment by jwendell** [comment]
Closed in favor of #774.

Weird, when I run locally it generates a 5000+ diff as well :/

**Comment by ericvn** [comment]
running `make clean` and `make gen` and new commit coming.

**Pull request closed without merging**
