### PR TITLE
Cherry-picks from master

### PR DESCRIPTION
**Pull request by ostromart**
Dynamic validation (#86)
Fix 'make generate-types' (#232)
Add e2e test for manifest migrate (#228)
add deployment strategy to IstioControlPlane k8s settings. (#234)
Add documentation to PilotConfig (#113)
Add documentation for tracing (#120) 
Add documentation to mixer policy (#122)
Add documentation to GalleyConfig. (#114)
Add documentation to SecurityConfig. (#115)
Add documentation for mixer telemetry (#116)
Add documentation to SidecarInjectorConfig. (#119)
Add documentation to ProxyConfig. (#118)
Add documentation to GlobalConfig. (#125)
add an option to regenerate testdata for unit tests (#235)
Fix output formatting (#233)
Fix typo (#238)
E2e tests for generate (#226) 
add --context and --kubeconfig support to manifest apply command (#237)
Update README (#209)
Updates to mesh command help text (#236)
Cleanup values_types.proto (#239)
Fix env value type (#244)
Add values validation (#227)
Add basic e2e tests (#242)
Fix logic for handling slice (#245)
Stabilizing manifest generation to create text diffable output (#249)

### CODE REVIEW

**Comment by brian-avery** [comment]
Hi @ostromart Can we please do a cherry-pick per issue? It will make it much easier to track.

**Comment by ostromart** [comment]
I've tried that previously but the individual cherry-picks tend to lead to ordering conflicts which become an even bigger headache. 
I have a pretty reliable method of tracking these and it gives me more control over what gets merged and when. If you guys have some nice ways of avoiding the reordering problem I'm happy to switch to that approach.

**Comment by brian-avery** [comment]
Thanks. Are all of these necessary for 1.3? There's only a couple of days before we cut the final release.

**Comment by ostromart** [comment]
The following are required:
Fix 'make generate-types' (#232)
add deployment strategy to IstioControlPlane k8s settings. (#234)
Fix output formatting (#233)
Fix typo (#238)
add --context and --kubeconfig support to manifest apply command (#237)
Update README (#209)
Updates to mesh command help text (#236)
Fix env value type (#244)
Stabilizing manifest generation to create text diffable output (#249)

however, the optional ones are just documentation and additional tests. IMO it's probably more risky to cherry-pick just a subset because there will probably be conflicts due to missing commits.

**Comment by ostromart** [comment]
@brian-avery @rlenglet will this get merged? Should we meet to discuss?

**Comment by brian-avery** [comment]
Hey @ostromart going through the PR now. So far not seeing any issues with it.

**Comment by ostromart** [comment]
Thanks!

**Review by rlenglet — COMMENTED** [review]
I have no objections to merging this.

**Review by brian-avery — APPROVED** [review]
I don't have any problems with this. Thanks.

**Pull request merged**
