### PR TITLE
update sha for installer to include automtls change

### PR DESCRIPTION
**Pull request by incfly**
istio/istio#14524

some test in ci is blocked on this.

### CODE REVIEW

**Comment by incfly** [comment]
https://github.com/istio/installer/commit/e8b6e534c78ed846d35ac46d1d88529e827aa7f0

**Review by howardjohn — COMMENTED** [review]
not super familiar with this, but I think there should be something about auto mtls here...

**Comment by incfly** [comment]
i did a run for the `make gen` and this asset.go is the only diff i got...

**Pull request closed without merging**
