### PR TITLE
Update the commonfiles and and update vfsgen

### PR DESCRIPTION
**Pull request by ericvn**

### CODE REVIEW

**Comment by ericvn** [comment]
Sounds like @sdake mentioned I should have removed the vsfgen, so putting a DNM until I can figure out the failure when that is added back in.

**Comment by ericvn** [comment]
Closing this PR and breaking things into pieces. I need part of this PR integrated first (to make the current code build/test in a container), then we can update the tooling to run build/test in containers (PR against test-infra), and then can make second set of changes here which require the containers portion to work.

**Comment by morvencao** [comment]
@elevran local build with `BUILD_WITH_CONTAINER=0` is broken, would you please have a look?
```
# make mesh
make[1]: Entering directory '/root/go/src/istio.io/operator'
go generate ./cmd/mesh.go
cmd/mesh.go:14: running "vfsgen": exec: "vfsgen": executable file not found in $PATH
Makefile.core.mk:25: recipe for target 'vfsgen' failed
make[1]: *** [vfsgen] Error 1
make[1]: Leaving directory '/root/go/src/istio.io/operator'
Makefile:77: recipe for target 'mesh' failed
make: *** [mesh] Error 2
```

**Comment by morvencao** [comment]
Build in container with `BUILD_WITH_CONTAINER=1` is all right:
```
# export BUILD_WITH_CONTAINER=1
# make mesh
Unable to find image 'gcr.io/istio-testing/build-tools:2019-08-07' locally
2019-08-07: Pulling from istio-testing/build-tools
d382a22f2872: Pull complete
3152c8398a28: Pull complete
930b821c67c4: Pull complete
4aa423fbf71b: Pull complete
5d039c38a870: Pull complete
227c6d9f08d5: Pull complete
c6776c64131b: Pull complete
Digest: sha256:94aa7fb596c9bf43e2cbf0c5d64093dfac5db5d1526eb624880aea20cc9ec348
Status: Downloaded newer image for gcr.io/istio-testing/build-tools:2019-08-07
go generate ./cmd/mesh.go
go: finding github.com/frankban/quicktest v1.4.1
go: finding github.com/google/go-cmp v0.3.0
writing ../pkg/vfsgen/vfsgen.gen.go
go build -o /work/out/bin/mesh ./cmd/mesh.go
```

**Comment by elevran** [comment]
@morvencao I believe the above was meant for @ericvn, not me...
Regardless, I think the issue is with a missing `vfsgen` module installed locally. It is installed inside the build container so `BUILD_WITH_CONTAINER=1` works, but not on your local machine:

```sh
elevran@elevran-dev:~/work/go/src/istio.io$ git clone git@github.com:istio/operator.git
Cloning into 'operator'...
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 24891 (delta 10), reused 18 (delta 6), pack-reused 24858
Receiving objects: 100% (24891/24891), 38.89 MiB | 4.14 MiB/s, done.
Resolving deltas: 100% (6680/6680), done.
elevran@elevran-dev:~/work/go/src/istio.io$ cd operator/
elevran@elevran-dev:~/work/go/src/istio.io/operator$ which vfsgen
elevran@elevran-dev:~/work/go/src/istio.io/operator$ BUILD_WITH_CONTAINER=0 make mesh
make[1]: Entering directory '/home/elevran/work/go/src/istio.io/operator'
go run ./cmd/vfsgen/vfsgen.go
cmd/vfsgen/vfsgen.go:25:2: cannot find package "github.com/shurcooL/vfsgen" in any of:
	/usr/lib/go-1.10/src/github.com/shurcooL/vfsgen (from $GOROOT)
	/home/elevran/work/go/src/github.com/shurcooL/vfsgen (from $GOPATH)
make[1]: *** [Makefile.core.mk:30: vfsgen] Error 1
make[1]: Leaving directory '/home/elevran/work/go/src/istio.io/operator'
make: *** [Makefile:77: mesh] Error 2
elevran@elevran-dev:~/work/go/src/istio.io/operator$ go get -u github.com/shurcooL/vfsgen
elevran@elevran-dev:~/work/go/src/istio.io/operator$ BUILD_WITH_CONTAINER=0 make mesh
make[1]: Entering directory '/home/elevran/work/go/src/istio.io/operator'
go run ./cmd/vfsgen/vfsgen.go
writing pkg/vfsgen/vfsgen_data.go
go build -o /home/elevran/work/go/bin/mesh ./cmd/mesh.go

```

The `vfsgen` part passes but fails on the next dependency. 
I don't know this code, so not sure if the operator has the right dependency set up for `vfsgen` in its Makefiles (may want to have all targets depend on getting the go modules, just to be safe...).

**Comment by morvencao** [comment]
@elevran Sorry, I mistake your github id for @ericvn,
And thanks for detailed explanation.
If you pull the latest operator code, the `make vfsgen` is working fine for both build in container and local env.

**Pull request merged**
