### PR TITLE
mesh profile dump generates ICPS CR format output.

### LINKED ISSUE #19692: istioctl profile diff generate unexpected outputs
I was following this doc:
https://preliminary.istio.io/docs/setup/install/istioctl/#show-differences-in-profiles

But the commands gave me different outputs:
`istioctl profile diff <(istioctl profile dump default) <(istioctl profile dump demo)`
```
 taohe@taohe:~/istio.io/operator$ istioctl profile diff <(istioctl profile dump default) <(istioctl profile dump sds)
Difference of profiles are:
 autoInjection:
   components:
     injector:
       enabled: true
       k8s:
         replicaCount: 1
         strategy:
           rollingUpdate:
             maxSurge: 100%
             maxUnavailable: 25%
   enabled: true
 cni:
...
...
```

`istioctl profile diff default demo`

```
 taohe@taohe:~/istio.io/operator$ istioctl profile diff default demo
Difference of profiles are:
 apiVersion: install.istio.io/v1alpha2
 kind: IstioControlPlane
 spec:
-  autoInjection:
-    components:
-      injector:
-        enabled: true
-        k8s:
-          replicaCount: 1
-          strategy:
-            rollingUpdate:
-              maxSurge: 100%
-              maxUnavailable: 25%
-    enabled: true
-  cni:
-    enabled: false
-  configManagement:
-    components:
-      galley:
-        enabled: true
...
...
```

### LINKED ISSUE #19804: mesh profile dump not generating ICPS CR format output
We should consider generating a ICPS which can be piped into `kubectl apply` cmd. `profile diff` should also get updated to support ICPS as input.

Current output of `mesh profile dump `
```
base:
  components:
    base:
      enabled: true
  enabled: true
...
```

Expected output
```yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  base:
    enabled: true
    components:
      base:
```

### PR DESCRIPTION
**Pull request by elfinhe**
Fix: https://github.com/istio/istio/issues/19804
Fix: https://github.com/istio/istio/issues/19692

### CODE REVIEW

**Review by richardwxn — COMMENTED** [review]
I remembered we had a discussion about this before? I think one problem is that if someone want to check the profile and apply then he can just simply run manifest apply <profile_name> right? Also it makes sense that dump only generates the config part value. Maybe add an extra option to choose to dump to ICPS CR format instead of changing the default now if we believe this is a UX improvement.

**Comment by howardjohn** [comment]
> Also it makes sense that dump only generates the config part value

Why? I never understood why that would be useful

**Comment by elfinhe** [comment]
> I remembered we had a discussion about this before? I think one problem is that if someone want to check the profile and apply then he can just simply run manifest apply <profile_name> right? Also it makes sense that dump only generates the config part value. Maybe add an extra option to choose to dump to ICPS CR format instead of changing the default now if we believe this is a UX improvement.

@richardwxn I have the same question as John. The specs only format is for internal use.

**Comment by ostromart** [comment]
Use of config-path flag will lead to invalid ICPs. That was one reason for not dumping the header. You'd have to ensure at least that you don't emit the header if that flag is used. For me this would seem an unintuitive and inconsistent UX.
Why is omitting the header a problem for users?

**Comment by howardjohn** [comment]
Because if you omit the header I cannot actually use the output without going copying the 1000s of lines of output, opening a text editor, trying to remember the header, indent all the output, and now maybe I can use it. I think in general the input format and output format should be the same as a general rule for tools, otherwise things get confusing/complicated

**Comment by howardjohn** [comment]
Although I didn't know about the config-path flag. Not sure how to reconcile that

**Comment by elfinhe** [comment]
> Because if you omit the header I cannot actually use the output without going copying the 1000s of lines of output, opening a text editor, trying to remember the header, indent all the output, and now maybe I can use it. I think in general the input format and output format should be the same as a general rule for tools, otherwise things get confusing/complicated

+1, now there are 2 versions of `istioctl profile`, e.g, https://github.com/istio/istio/issues/19692:

1.  `istioctl profile diff default demo` has header;
1. `istioctl profile dump` has no header;

for a complete ICPS file (i.e., dump/diff), we should print the header by default, which can be easily piped to `kubectl -f -` to create a CR.

as for --config-path flag and --set flag, the `spec` header can be omitted as input. Not sure if we need to output `spec` in this case.

**Comment by ostromart** [comment]
> Because if you omit the header I cannot actually use the output without going copying the 1000s of lines of output, opening a text editor...

It should be easy to prepend a header - is this just an indentation issue? 
If so, I propose adjusting the indentation in the output so you can just paste blocks directly without re-indenting. 
For --config-path indentation to be correct you can take the length of the path and use that to get the add the correct indentation.

**Comment by ostromart** [comment]
ping @howardjohn, is fixing the indentation acceptable here? see my comment above.

**Pull request closed without merging**
