### PR TITLE
WIP: test of the operator check for e2e

### PR DESCRIPTION
**Pull request by sdake**

### CODE REVIEW

**Comment by ostromart** [comment]
Hi @sdake, will you be able to make progress on this? Otherwise we should find another owner since it's quite critical.

**Comment by sdake** [comment]
@ostromart looks like @irisdingbj will take this over.  Note my original work was passing in my local environment and also prow.  There is some minor issue - possibly related to the usage of metallb - but possibly something else.

I'll take a look today after my morning meetings finish up.

Cheers
-steve

**Comment by sdake** [comment]
subsumed by work from @irisdingbj .

**Pull request closed without merging**
