### PR TITLE
Update common files

### PR DESCRIPTION
**Pull request by sdake**

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by richardwxn** [comment]
not sure why the gen-check kept failing. same issued for my PR although I updated the vfsgen files and tried running make gen multiple times locally

**Comment by sdake** [comment]
Depends-On: https://github.com/istio/common-files/pull/160

**Comment by sdake** [comment]
> not sure why the gen-check kept failing. same issued for my PR although I updated the vfsgen files and tried running make gen multiple times locally

The image in Makefile was not the same as used in CI.  This explains the discrepancy in environments.

**Pull request merged**
