### PR TITLE
update installer sha

### PR DESCRIPTION
**Pull request by carolynhu**

### CODE REVIEW

**Review by morvencao — COMMENTED** [review]
@carolynhu try to run `make gen` to fix the failed tests.

**Comment by carolynhu** [comment]
this repo is blocked by some issues right now, I will do it after it is unblocked

**Review by elfinhe — COMMENTED** [review]
/hold

I guess we are merging operator into isito. We can work on master later.

**Comment by ostromart** [comment]
We've merged installer and operator repos into istio so there's no need to sync anymore.

**Pull request closed without merging**
