### PR TITLE
Cherry-picks from master

### PR DESCRIPTION
**Pull request by ostromart**
Fix conflicts due to chart differences upstream (HEAD -> cp-5, origin/cp-5, release-1.3) 
Revert "Revert go-bindata due to release build issues (#241) (#248)" (#255) 
Improve error messages (#277) 
Update installer charts SHA (#279)
Doc updates. (#278)
Fix ordering of manifest diff output (#251)
Enable more linters in this repo. (#276) 
add toleration in k8s overlay settings (#269) 
Update common files. (#270) 
fix nodeselector path in k8s overlay. (#271)
Fix doc generation. (#268) 
Restore correct format for HTML docs (#267)
manifest diff: add text diff when --verbose flag is set. (#256)
Clean up IstioControlPlane proto for docs (#261)
Add kind setup back (#246) 
Fix html generation (#260) 
Fix proto patching hack (#259)

### CODE REVIEW

**Review by rlenglet — APPROVED** [review]

**Comment by ostromart** [comment]
@geeknoid I'm not sure why I can't see these lint errors in my local make lint. Would you mind checking if it works for you locally?

**Comment by geeknoid** [comment]
@ostromart 

The version of the build-tool container used by prow is different than the one you're introducing in this PR. Let me update prow to the right version, and then your local lint should agree with the prow lint.

**Comment by geeknoid** [comment]
Oh, I thought prow was behind, but it is actually ahead.

In this PR, please go in the top-level Makefile and replace the build-tools image with this version: build-tools:2019-09-17T18-24-15. Then you should see the same lint errors as prow is reporting.

**Pull request merged**
