### PR TITLE
WIP Prow test

### PR DESCRIPTION
**Pull request by sdake**

### CODE REVIEW

**Comment by fejta** [comment]
FYI if you make this a draft PR and/or have the title start with WIP (aka `WIP: do no merge prow test)` then the wip prow plugin (work-in-progress) will auto-add a label that will prevent tide from merging it.

You can also use the `/hold` and `/hold cancel` to add remove a hold label (or manage the label manually once it exists)

**Comment by ostromart** [comment]
@sdake can we close this PR? Seems like it's been absorbed into other work.

**Comment by sdake** [comment]
@ostromart I keep this PR open to test the gate.  I don't see any harm to keeping in the bottom of the queue?

**Comment by sdake** [comment]
will need a new test PR as prow is confused.

**Pull request closed without merging**
