### PR TITLE
[release-1.4] Fix affinity translation (#690)

### PR DESCRIPTION
**Pull request by richardwxn**

### CODE REVIEW

**Comment by mandarjog** [comment]
Q: @richardwxn  are simply giving ability to do pod affinity or configuring it in a specific way?

**Comment by howardjohn** [comment]
cherrypick of #690

**Review by howardjohn — APPROVED** [review]

**Comment by richardwxn** [comment]
@mandarjog this is for the manifest migrate command fix only, it doesn't change the way how we configure the affinity setting under k8s spec of IstioControlPlane CR

**Pull request merged**
