### PR TITLE
New installer with HPA fix

### PR DESCRIPTION
**Pull request by sdake**

### CODE REVIEW

**Review by ostromart — APPROVED** [review]

**Comment by richardwxn** [comment]
did you add the change to master? also you might need to update the profiles and test output

**Comment by sdake** [comment]
> did you add the change to master? also you might need to update the profiles and test output

I didn't change master as this is a 1.4 branch specific hash of installer.  I will look into the test failures.

thank you.

Cheers
-steve

**Comment by irisdingbj** [comment]
@sdake Thanks for taking care of this. Let me continue work on this to get the test failure cleared out.

**Comment by irisdingbj** [comment]
@sdake I am using https://github.com/istio/operator/pull/448 to consume all the installer changes now which fixed all the test failures.

**Comment by sdake** [comment]
Closing as #448 appears to work and pass the checks.

**Pull request closed without merging**
