### PR TITLE
Use gobuild.sh to build operator

### PR DESCRIPTION
**Pull request by ostromart**
This is required for version info to be populated during build time.

### CODE REVIEW

**Comment by ostromart** [comment]
@sdake could you ptal - I removed a line which appears to be redundant now. DNM until you approve.

**Review by howardjohn — APPROVED** [review]

**Comment by howardjohn** [comment]
should vfsgen change?

**Comment by ostromart** [comment]
you mean the generated assets? no, that is unexpected. all the generation should run before the controller binary is built and should not cause any change.

**Comment by ostromart** [comment]
interesting... after i run make clean gen again, the changes to assets.gen.go disappear.

**Comment by ostromart** [comment]
somehow this is caused by the deleted line. not sure why it has this effect - maybe @sdake can shed some light.

**Review by sdake — APPROVED** [review]
@ostromart I am not sure why a deleted line would imipact the vfsgen assets, but this PR LGTM.

**Pull request merged**
