### PR TITLE
Remove circleci

### PR DESCRIPTION
**Pull request by sdake**
This test is redundant and serves no purpose.

### CODE REVIEW

**Comment by ayj** [comment]
scripts/codecov_diff.sh also references circleci (see https://github.com/istio/operator/blob/d40f9e6fc1223cc35a8271c994d3e97385499cf6/scripts/codecov_diff.sh#L39-L71)

**Comment by sdake** [comment]
thanks @ayj

**Comment by richardwxn** [comment]
@sdake why we need to remove all code coverage scripts as well? I thought only the one supposed to run  on circleci need to be removed, the other one can be run locally

**Comment by elfinhe** [comment]
+1 We'd better keep the coverage script, which can be run locally. And the coverage script is referenced by Makefile.

**Pull request merged**
