### PR TITLE
fix controller panic.

### LINKED ISSUE #18041: Operator controller crash after deleting the ICP CR
With the latest code, after deleting the ICP CR, the controller panic:
```
2019-10-18T09:47:38.225627Z	info	Reconciling IstioControlPlane
2019-10-18T09:47:38.256495Z	error	error getting the unstructured of IstioControlPlane icp: istiocontrolplanes.install.istio.io "example-istiocontrolplane" not found
2019-10-18T09:47:38.256592Z	error	error getting IstioControlPlane icp: IstioControlPlane.install.istio.io "example-istiocontrolplane" not found
2019-10-18T09:47:38.256886Z	error	Observed a panic: &reflect.ValueError{Method:"reflect.Value.Type", Kind:0x0} (reflect: call of reflect.Value.Type on zero Value)
goroutine 265 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1725940, 0xc000863f00)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/runtime/runtime.go:51 +0x82
panic(0x1725940, 0xc000863f00)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
reflect.Value.Type(0x0, 0x0, 0x0, 0xc000248c20, 0x4)
	/usr/local/go/src/reflect/value.go:1877 +0x166
github.com/gogo/protobuf/jsonpb.(*Unmarshaler).unmarshalValue(0xc000863ec0, 0x0, 0x0, 0x0, 0xc000b68db0, 0x4, 0x8, 0x0, 0x40e2f8, 0x160)
	/go/pkg/mod/github.com/gogo/protobuf@v1.3.0/jsonpb/jsonpb.go:796 +0x5d
github.com/gogo/protobuf/jsonpb.(*Unmarshaler).UnmarshalNext(0xc000863ec0, 0xc000b78b00, 0x1c16d60, 0x0, 0x1a54490, 0xc000b68da8)
	/go/pkg/mod/github.com/gogo/protobuf@v1.3.0/jsonpb/jsonpb.go:758 +0x166
github.com/gogo/protobuf/jsonpb.(*Unmarshaler).Unmarshal(...)
	/go/pkg/mod/github.com/gogo/protobuf@v1.3.0/jsonpb/jsonpb.go:769
istio.io/operator/pkg/util.UnmarshalWithJSONPB(0xc000719b88, 0x5, 0x1c16d60, 0x0, 0xc000719b88, 0x5)
```

### PR DESCRIPTION
**Pull request by morvencao**
resolve: https://github.com/istio/istio/issues/18041

### CODE REVIEW

**Review by linsun — APPROVED** [review]

**Comment by elfinhe** [comment]
This and https://github.com/istio/operator/pull/415 should be added into release 1.4? it is blocking a PR to be cherrypicked into release-1.4: https://github.com/istio/operator/pull/445.

**Comment by ostromart** [comment]
Yes, it should, glad you caught that.

**Comment by morvencao** [comment]
@elfinhe Thanks.

**Pull request merged**
